import React, { Component } from 'react';   

class course1 extends Component {

    render() {
      return (
        <div>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          course1
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
        </div>
        );
  	}
}

export default course1;