# Generated by Django 2.1.1 on 2018-09-29 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='auth',
            field=models.ForeignKey(default=False, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
