# Generated by Django 2.0.7 on 2019-02-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_userthread_userthreadcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursecontent',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
