# Generated by Django 2.1.1 on 2019-02-05 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_userthread_userthreadcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChapterAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('aid', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(30)])),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserCourseContent')),
            ],
        ),
    ]
