# Generated by Django 2.0.7 on 2018-12-03 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181126_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Open',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='code',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='open',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Code'),
        ),
    ]
