# Generated by Django 2.0.7 on 2019-02-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userchapteranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchapteranswer',
            name='aid',
        ),
    ]
