# Generated by Django 2.0.7 on 2018-12-27 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_techinfo_usertechinfo_usertechinfocomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('auth', models.ForeignKey(default=False, on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adque',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ads'),
        ),
    ]
