# Generated by Django 2.1.1 on 2019-01-14 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20181227_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertiList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('name', models.ForeignKey(default=False, on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
