# Generated by Django 2.0.7 on 2019-01-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_certilist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certilist',
            name='code',
            field=models.CharField(max_length=128),
        ),
    ]
