# Generated by Django 2.0.7 on 2019-01-17 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190115_0952'),
        ('api', '0008_auto_20190115_1651'),
    ]

    operations = [
    ]
