# Generated by Django 2.0.7 on 2019-01-17 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20190117_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certilist',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
