# Generated by Django 2.0.7 on 2019-01-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_usercourse_usercoursecontent_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursecontent',
            name='cid',
            field=models.IntegerField(default=-1),
        ),
    ]
