# Generated by Django 2.0.7 on 2019-01-22 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_usercoursecontent_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('createat', models.DateTimeField(default=django.utils.timezone.now)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserCourse')),
            ],
        ),
    ]
