# Generated by Django 2.0.7 on 2019-01-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_usercoursecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoursecontent',
            name='likes',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
