# Generated by Django 2.0.7 on 2019-01-22 04:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190122_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseContentIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createat', models.DateTimeField(default=django.utils.timezone.now)),
                ('context', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usercoursecontent',
            name='code',
        ),
        migrations.AddField(
            model_name='usercoursecontentindex',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserCourseContent'),
        ),
    ]
