# Generated by Django 2.1.1 on 2019-01-22 09:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190122_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseContentCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createat', models.DateTimeField(default=django.utils.timezone.now)),
                ('context', models.TextField()),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserCourseContent')),
            ],
        ),
    ]
