# Generated by Django 2.0.7 on 2019-01-23 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_usercoursecontentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursecontentcode',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserCourseContentIndex'),
        ),
    ]
