# Generated by Django 2.1.1 on 2019-01-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190123_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='users',
            field=models.IntegerField(default=0),
        ),
    ]
