# Generated by Django 2.0.7 on 2019-01-25 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_usercourse_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercoursecontentcode',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserCourseContent'),
        ),
    ]
