# Generated by Django 2.0.7 on 2019-01-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190125_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stuff',
        ),
        migrations.DeleteModel(
            name='Testboard',
        ),
        migrations.RemoveField(
            model_name='testuserauth',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='testuserf',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='testuserlive',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Totest',
        ),
        migrations.DeleteModel(
            name='TestUser',
        ),
        migrations.DeleteModel(
            name='TestUserAuth',
        ),
        migrations.DeleteModel(
            name='TestUserF',
        ),
        migrations.DeleteModel(
            name='TestUserLive',
        ),
    ]
