# Generated by Django 2.1.1 on 2019-01-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190125_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursecontentindex',
            name='sid',
            field=models.IntegerField(default=-1),
        ),
    ]
