# Generated by Django 2.0.7 on 2019-01-30 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190125_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
