# Generated by Django 2.0.7 on 2019-02-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userinfo_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursecontent',
            name='code',
            field=models.CharField(default='tste', max_length=128),
            preserve_default=False,
        ),
    ]
