# Generated by Django 2.0.7 on 2019-01-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userinfo_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursecontent',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
