# Generated by Django 2.0.7 on 2019-02-01 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_usercoursecontent_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoursecontent',
            name='code',
        ),
    ]
